version: "3.5"

networks:
  nginx-php-postgres:

services:
  # nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-to-do
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - nginx-php-postgres

  # php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-to-do
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-php-postgres

  # postgresql
  postgres:
    image: postgres:latest
    container_name: postgres-to-do
    ports:
      - "7432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    networks:
      - nginx-php-postgres

volumes:
  db_data:
